# Generated by Django 4.0.5 on 2022-06-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created']},
        ),
    ]
